### ISSUE TITLE
Missing shebang in doctum.phar

### ISSUE THREAD

**Issue by ptomulik** [code-lts/doctum#17]
Hi, I've just downloaded doctum.phar from https://github.com/code-lts/doctum/releases/tag/v5.2.0. The phar is missing sheabang (the first line, which usually should be ``#!/usr/bin/env php``), so I can't just run it by ``./doctum.phar`` (must use ``php doctum.phar``). Not so important, but most phars I've seen have sheabangs in it.

**Comment by williamdes** [comment]
Hi, I agree about that
I just have to check that adding one would not break current calls `php doctum.phar`

Thank you for the issue, I never did worry about that because like you said the documentation says to use `php`

**Comment by williamdes** [comment]
I just released 5.3.0-dev phar, I just found out where my mistake was on my previous attempt on the official docs: [here](https://www.php.net/manual/fr/book.phar.php#121323)
