### ISSUE TITLE
Release v5

### ISSUE THREAD

**Issue by williamdes** [code-lts/doctum#2]
# Version 5.0

Version 5.0 will be released some day, soon I hope.

The changelog is here: https://github.com/code-lts/doctum/blob/main/CHANGELOG.md#unreleased

Links:
- https://github.com/phpmyadmin/scripts/issues/27
- https://github.com/phpmyadmin/phpmyadmin/issues/14644

**Comment by williamdes** [comment]
@fabpot I just want to :ping_pong: you here, the project is forked and renamed.

I left the "This file is part of the Sami utility."
Would you mind if I remove them ?
https://github.com/code-lts/doctum/search?q=Sami&unscoped_q=Sami

**Comment by fabpot** [comment]
As long as you keep the copyrights and the licenses, I would indeed encourage you to remove any mention of the Sami name.

**Comment by williamdes** [comment]
Thank you for the advice, I replaced the name and kept the headers.
I think I will release a version this week, would you agree to link Doctum on the Sami repository ?

**Comment by williamdes** [comment]
The release will be done when all the work assigned to the milestone is done.

**Comment by williamdes** [comment]
https://github.com/code-lts/doctum/commit/f952902aace3c48f6f7fe760074dd31b56435089
https://github.com/code-lts/doctum/releases/tag/v5.0.0

**Comment by williamdes** [comment]
@fabpot The project is released and has a website https://doctum.long-term.support/ (quite minimal but still)
Would you agree to link the project on the Sami repository ?

**Comment by williamdes** [comment]
@keevitaja 
https://laravel.io/forum/sami-documentation-generator-alternatives
