### ISSUE TITLE
 "3" @param tags are expected but only "4" found

### ISSUE THREAD

**Issue by ptomulik** [code-lts/doctum#21]
I happened to see this message:
```console
ERROR: "3" @param tags are expected but only "4" found
```

"only 4" looks funny when compared to 3 :)

**Comment by williamdes** [comment]
This error is very very annoying, I need to remove it in the next release.
If the parameter has documentation by its typehint, then do not add a new error.

**Comment by ptomulik** [comment]
>[...]
> If the parameter has documentation by its typehint, then do not add a new error.

This would be nice, especially that [php-cs-fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer) removes non-contributing ``@param`` docblocks when using [@PhpCsFixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/2.17/doc/ruleSets/PhpCsFixer.rst) rule set, or its subset [@Symfony](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/2.17/doc/ruleSets/Symfony.rst), see the [no_superfluous_phpdoc_tags](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/2.17/doc/rules/phpdoc/no_superfluous_phpdoc_tags.rst) setting. I guess these rulesets are used quite commonly.

**Comment by williamdes** [comment]
Hi, I released the `5.3.0-dev` phar so you can have a try and let me know.
The messages should be better now
