### ISSUE TITLE
PHP 8.0 compability

### ISSUE THREAD

**Issue by shyim** [code-lts/doctum#34]
Hey,

I saw that doctum throws many deprecation when it is executed on PHP 8.0 like

ERROR: 8192: Method ReflectionParameter::getClass() is deprecated in phar:///home/shyim/Code/opensearch-php/doctum.phar/vendor/phpdocumentor/reflection-docblock/src/DocBlock/StandardTagFactory.php line 241 on "OpenSearch\Client::$transport" in /home/shyim/Code/opensearch-php/util/../src/OpenSearch/Client.php:86

I expect the library needs just to bump up reflection-docblock 🤔

**Comment by williamdes** [comment]
Hey @shyim 

What version of the Doctum phar are you using ?
It is compatible with PHP 8.0 since some versions :)

Even our GitHub action uses php 8: https://github.com/sudo-bot/action-doctum

Let me know

**Comment by shyim** [comment]
Hey,

I use currently the phar `https://doctum.long-term.support/releases/5.3/doctum.phar` as spaceless filter is removed (due Twig upgrade?) in 5.4 :)

**Comment by williamdes** [comment]
> Hey,
> 
> I use currently the phar `https://doctum.long-term.support/releases/5.3/doctum.phar` as spaceless filter is removed (due Twig upgrade?) in 5.4 :)

Oh, are you using a custom theme then ?

Maybe you can use this commit as an example to migrate: https://github.com/phpmyadmin/phpmyadmin/commit/bd33d92f39e7b0ea91aa96a3766207d389483927

**Comment by shyim** [comment]
Yes this one https://github.com/elastic/elasticsearch-php/tree/master/util/docstheme as I forked from here :)

As I read the changelog it should work also with 5.3 or? :thin

**Comment by williamdes** [comment]
Oh wait 😄 
Look, the work is here but nobody did care: https://github.com/elastic/elasticsearch-php/pull/1128

**Comment by shyim** [comment]
Are you fine when I import that into the OpenSearch client? 😄

**Comment by williamdes** [comment]
> Are you fine when I import that into the OpenSearch client?

Sure, you can fetch the patch: https://github.com/elastic/elasticsearch-php/commit/40d0d86fdf609be733751f1688540e0b167ea7f7.patch

Please set me as the author of the commit or add a `Co-Authored-By: William Desportes <williamdes@wdes.fr>` in the commit body ;)

**Comment by shyim** [comment]
Imported and it runs without deprecations. Thanks! ❤️ 

For a future guys searching for the commit, that's the pull request link: https://github.com/opensearch-project/opensearch-php/pull/5 (Is currently private as we prepare the repository)

**Comment by williamdes** [comment]
I am very happy that it works great!
Thanks for opening this issue
