### ISSUE TITLE
Theming - Striping in left sidebar off-alignment with text

### ISSUE THREAD

**Issue by bradjones1** [code-lts/doctum#42]
![Screenshot 2021-12-20 at 12-46-00 Namespaces Drupal Core API Explorer](https://user-images.githubusercontent.com/981966/146831174-0134ff14-6d0f-4123-8ede-cd6660fac2e2.png)

This is on Firefox. I actually don't see the striping at all on Chromium. It kinda-sorta appears when I'm using the element inspector (beyond the blue selection highlight) but not there at all when viewing as an end-user.

I'm not amazing at CSS so I'm not sure the "right" way to do this? Something with `:nth-child()` is the first thing that comes to mind but nesting makes that complicated.

**Comment by bradjones1** [comment]
If the actual dataset matters: https://api.rtdm.info/9.3.0/

**Comment by williamdes** [comment]
Yeah, this part should be re-written probably
The tree is some kind of JS build node list and the css is not aware of the item list If I recall correctly

A lot of place for new and cool code ^^

**Comment by williamdes** [comment]
I would recommend you to try the latest dev phar as much as possible to test it until I make the final fixes for a release, see: #38

Thank you so much for the link, I may add your project to the README ;)

**Comment by williamdes** [comment]
Oh this seems to be a Firefox only CSS issue

**Comment by williamdes** [comment]
Hi @bradjones1 
The version [5.5.0](https://github.com/code-lts/doctum/releases/tag/v5.5.0) is out 🎉 
This fix is included in the version released
