### ISSUE TITLE
Do as the documentation said to install and got some problem

### ISSUE THREAD

**Issue by pndx** [code-lts/doctum#46]
Follow the documentation and got some problem.
1. download the `doctum.phar`
2. create a php file `generateDocumentation.php`
    ```php
    <?php
    return new \Doctum\Doctum(__DIR__);
    ```
4. run `php generateDocumentation.php` from cli and got the follow error.
    ```
    PHP Fatal error:  Uncaught Error: Class "Doctum\Doctum" not found in D:\htmlGenerator\generateDocumentation.php:3
    Stack trace:
    #0 {main}
      thrown in D:\htmlGenerator\generateDocumentation.php on line 3
    ```

**Comment by pndx** [comment]
I solve it by `require __DIR__.'/doctum.phar';`

**Comment by williamdes** [comment]
Hi @pndx 
What was your command line ?

In our tests this line is not needed, see: https://github.com/code-lts/doctum/blob/main/tests/phar/tests.sh

https://github.com/code-lts/doctum/blob/main/tests/phar/data/doctum-relative.conf.php

**Comment by pndx** [comment]
@williamdes yes, is not needed. I think is wrong way to use it earlier. Now i use `php doctum.phar update doctumConfig.php`. and the code of doctumConfig.php is below.
```php
<?php
/**
 * Run `php doctum.phar update doctumConfig.php` to generate api documentation.
 */

use Doctum\Doctum;
use Symfony\Component\Finder\Finder;

$iterator = Finder::create()->files()->in(__DIR__ . '/app');
return new Doctum($iterator, [
    'title' => 'example',
    'language' => 'en',
    'build_dir' => __DIR__ . '/documentation',
]);

```

**Comment by williamdes** [comment]
Very cool to hear that @pndx 🎉
the language key is not needed if you use it's default value

And if you `chmod  +x doctum.phar` then you can remove `php` in your command line to run Doctum :)
