### ISSUE TITLE
Multiple Branches at GitHub Action - Returns Single Branch

### ISSUE THREAD

**Issue by lrljoe** [code-lts/doctum#61]
When using the published GitHub Actions on a push/pull.

Then in the config referencing multiple branches.

Sadly, in this use case, only one branch is returned, unless I'm doing something very wrong.

When using it on-prem by pulling down a repo, and running the doctum.phar tool, it works fine, just not via GH Actions.

I'm suspecting that we just need to lower our expectations, and run everything manually.

**Comment by williamdes** [comment]
Hi !

I have an idea, it is probably about your use of `actions/checkout` 
Can you post your workflow file ?
Or repo link ?

**Comment by lrljoe** [comment]
Will do this eve, I managed to workaround it somewhat in a test fork, but it misbehaved in the original fork.

I'll get all of the branches and the workflow in one place this evening UK time.

Apologies for the lack of detail initially!

**Comment by williamdes** [comment]
No worries :)

Did you figure out something ?


I think you need: to set `fetch-depth: 0` for https://github.com/actions/checkout
See: https://github.com/actions/checkout#fetch-all-history-for-all-tags-and-branches

**Comment by lrljoe** [comment]
Cheers, will give that a try and update if not.  The challenge is always updating workflows in packages that are used by 1m websites, and not breaking too much ha.

**Comment by williamdes** [comment]
Let me know if you need some more help :)
